### ISSUE TITLE
Flutterfire Configure Komutu

### ISSUE THREAD

**Issue by Asimtarik** [VB10/mycodingsetup#10]
flutterfire configure komutunu yazdığımda şu hata ile karşılaşıyorum;

FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase --version
ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it. 

    FlutterFire CLI ve Firebase CLI kurulu olmasına rağmen bu hatayı alıyorum. FirebaseCLI referans sayfasından Windows için Firebase CLI ikili dosyası olan 'firebase-tools-instant-win' üzerinden her ikisinin de versiyonunu 'flutterfire -V' ve 'firebase --version'  komutları ile görebiliyorum. Projeye girip aynı komutu denediğimde ise yukarıdaki hatayı alıyorum.

    Bir diğer yöntem olarak gösterilen  npm komutunu kullandığımda da bu hatayı alıyorum;

 npm install firebase-tools@12.4.4
Error: double-loading config "C:\Users\Lenovo\.cache\firebase\runtime\npmrc" as "global", previously loaded as "user"
    at Config.#loadObject (C:\snapshot\firepit\node_modules\npm\node_modules\@npmcli\config\lib\index.js:571:13)
    at C:\snapshot\firepit\node_modules\npm\node_modules\@npmcli\config\lib\index.js:617:31
    at async Config.#loadFile (C:\snapshot\firepit\node_modules\npm\node_modules\@npmcli\config\lib\index.js:616:5)
    at async Config.load (C:\snapshot\firepit\node_modules\npm\node_modules\@npmcli\config\lib\index.js:287:5)
    at async Npm.#load (C:\snapshot\firepit\node_modules\npm\lib\npm.js:195:5)
    at async C:\snapshot\firepit\node_modules\npm\lib\cli-entry.js:40:5

 Bu iki hata ile ilgili internet üzerinde bir çözüm bulamadım. Yardımcı olursanız sevinirim.

**Comment by mrjake34** [comment]
FlutterFire kurulu olabilir de doğru terminali kullandığına emin misin bazen kurulumu PowerShell e yapıyor windows path i de powershell için veriyor, cmd yada powershell ikisini de deneyebilirsin vs code terminal kısmından
