### ISSUE TITLE
İl ve ilçe Api 

### ISSUE THREAD

**Issue by berkyoruk** [VB10/mycodingsetup#13]
veli hocam selamlar bi projede il ve ilçeleri aramaya göre listelemem gerekiyor ancak bununla ilgili bi api bulamadım daha önce hazırlanmış bu json u buldum , bunu projeye nasıl dahil edebilirim veya bunu bu şekilde projeye dahil edersem ne kadar mantıklı olur  https://github.com/snrylmz/il-ilce-json/blob/v1.0.1/js/il-ilce.json
Yapmak istediğim şey şu 

![a](https://github.com/VB10/mycodingsetup/assets/120643757/fc2884e9-6d52-4f16-8858-278fa91fa20b)
konum seçiniz yazan yere yazmaya başladığında il ilçe olacak şekilde Listelenecek (izmir,buca) gibi

**Comment by mrjake34** [comment]
Seçim dönemin de bir çalışma yapmıştım istediğin sistemi denedim json ile fakat bunu direk adres olarak yapan paketler de var, google vs gibi haritalar üzerinden de çekiyorlar
https://github.com/mrjake34/secim_tutanak_takip_2023cb
